spring:
  application:
    name: stream-demo
  rabbitmq:
    host: localhost
    port: 5672
    username: springcloud
    password: 123456
    virtual-host: cloud-demo
  cloud:
    stream:
      bindings:
        input:
          destination: output
        output:
          destinations: input