spring:
  application:
    name: feign-consumer
  profiles:
    active: dev
server:
  port: 9001
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1111/eureka/
feign:
  hystrix:
    enabled: true
