spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Eliefly/spring-cloud-learning
          search-paths: config-repo
          username: username
          password: password
server:
  port: 7001


## HystrixCommand 执行超时时间
#hystrix:
#  command:
#    default:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 70000
#
#ribbon:
#  # 创建请求连接的超时时间
#  ConnectTimeout: 60000
#  # 转发请求的超时时间
#  ReadTimeout: 600000